// ─────────────────────────────────────────────────────────────────────────────
// agents/scribe/dashboard.ts
// Builds the markdown audit trail comment that Scribe posts on each MR.
// Also generates a summary for the GitLab project's dashboard issue.
// ─────────────────────────────────────────────────────────────────────────────

import { ComplianceNote, GeneratedFix, PatchPilotResult } from "../../lib/types";
import { ComplianceMapping } from "./compliance-mapper";
import { now } from "../../lib/utils";

/** Builds the detailed audit markdown posted as a comment on the fix MR */
export function buildAuditComment(
  fix: GeneratedFix,
  mapping: ComplianceMapping
): string {
  const { finding } = fix;
  const timestamp = now();

  const frameworkList = mapping.frameworks.length
    ? mapping.frameworks.map((f) => `- ${f}`).join("\n")
    : "- No specific framework mapping found";

  const referenceList = mapping.references.length
    ? mapping.references.map((r) => `- ${r}`).join("\n")
    : "- No external references";

  return `## 📋 PatchPilot Compliance Report

*Generated at: ${timestamp}*

### Finding Summary
| | |
|---|---|
| **ID** | \`${finding.id}\` |
| **Name** | ${finding.name} |
| **Severity** | **${finding.severity.toUpperCase()}** |
| **Location** | \`${finding.location.file}:${finding.location.start_line}\` |
| **Confidence** | ${finding.confidence} |

### Fix Explanation
${fix.explanation}

### Compliance Frameworks Addressed
${frameworkList}

### References
${referenceList}

---
*This fix was autonomously generated by [PatchPilot](https://gitlab.com/gitlab-ai-hackathon). Always review before merging.*`;
}

/** Builds a high-level summary for the run — useful as a project issue or pipeline comment */
export function buildRunSummary(result: PatchPilotResult): string {
  const duration = Math.round(
    (new Date(result.completedAt).getTime() - new Date(result.startedAt).getTime()) / 1000
  );

  const mrLinks = result.fixes
    .filter((f) => f.mergeRequestUrl)
    .map((f) => `- [${f.finding.severity.toUpperCase()}] [${f.finding.name}](${f.mergeRequestUrl})`)
    .join("\n");

  return `## 🤖 PatchPilot Run Summary

| | |
|---|---|
| **Run ID** | \`${result.runId}\` |
| **Started** | ${result.startedAt} |
| **Duration** | ${duration}s |
| **Total findings** | ${result.totalFindings} |
| **Dismissed (noise)** | ${result.dismissed} |
| **Fixed** | ✅ ${result.fixed} |
| **Failed** | ${result.failed > 0 ? `❌ ${result.failed}` : `0`} |

### Merge Requests Opened
${mrLinks || "None"}

---
*PatchPilot — Autonomous security remediation for GitLab*`;
}
