// ─────────────────────────────────────────────────────────────────────────────
// agents/fixer/gitlab-mr.ts
// After Claude generates a fix, this module:
//   1. Creates a new git branch
//   2. Commits the patched file
//   3. Opens a Merge Request
// All via the GitLab REST API — think of it like calling a GitHub API from Express.
// ─────────────────────────────────────────────────────────────────────────────

import { GitLabClient } from "../../lib/gitlab-api";
import { FixRequest, GeneratedFix } from "../../lib/types";
import { ClaudeFixResult } from "./claude-client";
import { buildBranchName } from "../../lib/utils";
import { logger } from "../../lib/logger";

const log = logger("Fixer:GitLab");

function buildMRDescription(
  req: FixRequest,
  fix: ClaudeFixResult
): string {
  const { finding } = req;

  return `## 🤖 PatchPilot — Automated Security Fix

> This Merge Request was automatically generated by **PatchPilot**, an AI-powered security remediation agent.

### Vulnerability
| Field | Value |
|---|---|
| **Name** | ${finding.name} |
| **Severity** | ${finding.severity.toUpperCase()} |
| **File** | \`${finding.location.file}\` |
| **Line** | ${finding.location.start_line} |
${finding.owaspCategory ? `| **OWASP** | ${finding.owaspCategory} |\n` : ""}${finding.cweId ? `| **CWE** | ${finding.cweId} |\n` : ""}

### What was wrong
${finding.description}

### How it was fixed
${fix.explanation}

---

**⚠️ Please review this fix before merging.** PatchPilot is an AI assistant — always verify the change is correct for your codebase.

/label ~"security" ~"patchpilot" ~"${finding.severity}"`;
}

export async function createFixMR(
  gitlab: GitLabClient,
  req: FixRequest,
  fix: ClaudeFixResult,
  branchPrefix: string,
  defaultBranch: string,
  dryRun: boolean
): Promise<GeneratedFix> {
  const { finding } = req;

  const branchName = buildBranchName(
    branchPrefix,
    finding.id,
    finding.location.file
  );

  if (dryRun) {
    log.warn(`DRY RUN — would create branch: ${branchName}`);
    return {
      finding,
      patchedContent: fix.patchedContent,
      explanation:    fix.explanation,
      branchName,
      mergeRequestIid: undefined,
      mergeRequestUrl: undefined,
    };
  }

  // 1. Create the fix branch
  await gitlab.createBranch(branchName, defaultBranch);

  // 2. Commit the patched file to that branch
  await gitlab.commitFile(
    branchName,
    finding.location.file,
    fix.patchedContent,
    `fix(security): patch ${finding.name} in ${finding.location.file}\n\n${fix.explanation}\n\nRemediated by PatchPilot`
  );

  // 3. Open the Merge Request
  const mr = await gitlab.createMergeRequest({
    sourceBranch: branchName,
    targetBranch: defaultBranch,
    title:        `[PatchPilot] fix(${finding.severity}): ${finding.name}`,
    description:  buildMRDescription(req, fix),
    labels:       ["security", "patchpilot", finding.severity],
  });

  log.success(`MR opened: ${mr.web_url}`);

  return {
    finding,
    patchedContent:  fix.patchedContent,
    explanation:     fix.explanation,
    branchName,
    mergeRequestIid: mr.iid,
    mergeRequestUrl: mr.web_url,
  };
}
